# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:3wI6TmW4sOHj,iv:t8bWpZ1jtIkcrleXUJnuLAqn2lEl/yjTtFpMnBmMcyw=,tag:HOF1FyVuKCd8dc7uE8s2LA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:qel252PugAeWHGTBXnOB+RgaGmXp9IA=,iv:/bvNeSE7BxIw9WE74gWQbclk955dfa+gUx325Bh+5HE=,tag:9tbnOWvUu1TEm8yQkgE5gQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-30T12:18:36Z"
    mac: ENC[AES256_GCM,data:oa6CRPtN5XqD8Q0njksZMscl0469wmNZmlH9hD0WckgCo61vjnyf81E5vPNkB5MzvW4n/Tg0K5NramUoGv53lMXVFl+00V8N3N470JldTXVWvBRqDpc4gz9MglUMWMhexYqQKeGOQtWabXZ4MuhqpKObHW9k9HmJaaNXhCXThpY=,iv:pmsMkhhfNMl7QzhFRfr3ht7mqGADRkT/eSx0x3gtxhc=,tag:JFcc5IfzDC29Lt+rSFEOyg==,type:str]
    pgp:
        - created_at: "2021-07-30T12:18:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9vmVmtnXzfkAQ/+MKdtu3FIW9zZgtYPg5CGMu5Cbks1hPS+5cwSrTE6H/Ml
            X3QJGCevQQzOqWniTGMr5NnXjMeELAHVlTQ5oWGKNplKm1SlcLBHfbDmeVbrwOq1
            ZAUFN0IHEa4KhWnjesTBHUEj2i4/z11fSl3ufSvm5ARps6lnI8SJDQfcR35uovLj
            VcK26iDeU+NGiedf623Bwfu7zShdalG809Ltxh58ilIHrIG79O2Nd5Cg2TyFXdz5
            Kt4pAVweFseAOdoTiVxYJ7IX/C8SiWpKu+jHcmWWqHKx+2Nvo+kQ2qXCaVRKAXVK
            oPr8PB4vbSdikV69z72BwwVOlESZl9W76RBc2NHMysGe6+N5qXoDoTa+f3mIEH44
            5J6//5C1zNQnDnVZdkvm9nnG6W/Q5Bnbyaf+rBv/QU06kQIqV1u/vN2BwCNetlPt
            AO1vLqWMrGZnEAPtbOSt3M0qA78w+yxjmdFQjN2coH9B7Gj7URnlGGmtu1BL+Gi+
            u4G8m1Jbi7hDIOS9XbYqqwBX2eNL/TY8ezTNGrJwvbcocMDue8dhdiJPCPsE7ZyS
            gyDmFILJN3Hj5Ag6pSJ45sX8jk0bNN7cIzoAL+AQh1rr65G+YUdb9isO8Z37oNnf
            gS+Ug1FLZ6hhy3dYh5t1N+6ZisFVlj4DfK7b8QcOrJgXgB8IMVixy5HOFZ6MWbfS
            XgE0/JiVLvaQIgJXO2zx3eHgwh/y3aFjNwFyHwzobn8sazHmk3bRrHGcIjGOE7fY
            2/IZrJwHaYKBHl6eAcWoObco1t18ImDSElxyU6Nk2Qic5Mq7Ub6/BxcC13FOPeg=
            =r8o+
            -----END PGP MESSAGE-----
          fp: F81B6EF89D5F99C9C850D4AADF526615AE65841D
        - created_at: "2021-07-30T12:18:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5X7/W3ld7fGAQ//WapnT/fXofjenI2yAcO3VZJj/CJYFpVKfVljCAvPIELm
            GHSHc3+hMbnGyxOEQGqTdMQilt2LgWIcs36ODXZVu2GeJ0gDF/J6zSIy+9ar1D8S
            83Mjfs5PhVGP0rJvxQ2HRoZKLfOyP1yVDJbb31KqowRw+h08foGLlPuOAVAfpiKd
            4QvpXcgedLRBUdGz6DEa3kcWEb9imTfQkrjFUTD+dCT533iSqMwFLVnp52RhRCN5
            r+f3/8l8rRQ3yVhZh/tmtQhT/+AkOdnDJvJ+zSYOkkFtML1XWMSkL6gRAn+yMwFS
            nw782jUvHMzUEsWWccDrZVGRnKhk6dV+qJzXQfiZA88TrmlNgIM6uQJobHmFLfbH
            Ox84Ycj0qcbnzT57uq/5NtwHY+kZyuQj9muOJcLcKMPQeYuC2DS2buxsHqNNXsAV
            8LMo7HHLQ/fbhWw/YXWziIrsoLZ84JpFIQH/BLXs/vb9KvVAB7oVzsBQuSGE5Ca1
            /fs/d+GMR755ikjnTgYpoI2Jk93+YgeXyX1RgBHZBIaUSPig0G+zjf/TVmEbl4bM
            BZsj+daMv/LMQy+wVeC8/xJFu+ysUYlHL0oQZAUa2m8Tf3pzi+XnKe5F6Ab+fAYy
            2lrv3FsuhW5GJcLPUI2/Ss61goJp2yf3Gv7JUTspdslMdI6Z1EVgOjB14FVEAQ3S
            XgEiHcXJo042tVI+9f8ea1XEuYs0Lxl99orWA/6rwiMU8zNzLYJ8UbPfCwWrBn8I
            elkgofC0SIU0toHK8fNFETFGhbVbnJXShwDgd2GAWyDENwfLB/dwE4xN64hv/yY=
            =IXmK
            -----END PGP MESSAGE-----
          fp: D1119E5D8F229217E32C7E7345017EA78B63F284
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
