# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:69SWoKdBuSoG2isLDfJPNyS3L9ZPLm4OlYd2QndtE9AwNm/uuFeu1g==,iv:LKIQ6pU0XqJHrCt3Rs2AeqevADjSMOW/ryy9xwbZGVY=,tag:clwFumK1NyJtZ1yw2F1T3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-30T12:19:47Z"
    mac: ENC[AES256_GCM,data:a/nT8wXZr0PHjuukrNdWJ5qC/OCkBXzIMjnS5EMhnwkKgTXOisxkcCJr6LsW5/BXZBbvyE1f8OZqO3uBdqK7LbVF5tVhWRjH8ccEeAD4t/mrP7Ik/0/VoSsfVn8HDPFbVXLP74SUQouS8IIHYRP38b+BKXhYeRUcwz0kbYxpQqk=,iv:6HVyGKjaMjuIewQ+eT8fV59/XZFULFRok0Zh6RN/nFM=,tag:cjG3zCqTl1wXRk36YrzogQ==,type:str]
    pgp:
        - created_at: "2021-07-30T12:19:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9vmVmtnXzfkAQ//b388eIGJSKi300mXqKlVtSbVqs2ymmtwfmoPvP55ux5Q
            LM5Opek+NsKbaYQoukC+wxNHoIc5GZkyaiwmYrVd3GKoZKPHZvrPJq2g/t9LPqVR
            TjQKK1M7+p3PhFu2UcCZ+Mjt09dHYFF/6a0zrcpBZQWZMgLS7Ci+ujK4QhK1Cqfd
            Vf8si4+Bds1NkGJ/ZUZ0ATE2gfmWJT5gEziw5p+hfHmX4boHSZ7Wuha0L/TSWsut
            kIhAB81ej4+3QCJcJW5ghz0Utc3OQwC1P4nGGf0zmDRJmgMuKg1hQ+ny34i1iPnA
            Yw0AzHquiPSPWolxfrQzMPQw9HuqIP6jvc79cXFFmHDcx1wFYn6MxP/X3MLA4oKS
            o5axQ+A2t5nzcAq+gUi4F1Majz82IkZgqqeyoDGZhHtbShZNEzAeQgfSmEM0xfXE
            KKMptPlPo1718+/lLUYcDg8EUrAVHznbimEsoaHbObIEhiBZPLp2CBiJ1xupBg2z
            ovXAwDIv2Wj2ZqckwITZ2h000TnavA2GfIMQo+usltezG2941edVPo37+K13lJ9e
            L0ONmOIf0Zt+wqdMC5KR5DiYKUA28SERX96wlXfbi28pLP34Rh7sgpgZ+qgqTlKx
            arU8jqTVaPoP86vCDqlYP7Db8fABl9gSJ/ZK2O8ZR0y+fR0NdieyHHzvI96ZjFDS
            XgHQxZ4KzNCuF/PGh9+apL5q5GJlmWcTtRTIbzXxviZdnrNfNtYw4qmAI0PK5Xr7
            T2oNmTbFnWk5b/EWRHmB5y2ILGyLFrQnpYRjC5FXr1esvW+ogcQZz8tjkAMypDI=
            =PggJ
            -----END PGP MESSAGE-----
          fp: F81B6EF89D5F99C9C850D4AADF526615AE65841D
        - created_at: "2021-07-30T12:19:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5X7/W3ld7fGAQ/+MLPA9+HGNCkJgsU1HgKKkE55OxqsW397x6r0j6wYf6Cz
            UURsf0XkCamntTC3KATZHzqjlexc+tbL0lMRwkWxHdW0v6nPG/wQyQPByc/xV3KD
            ZQHScqgALb3IAyG8sg9HMVNmnzwmqWkB6zJ2SOC47yAMsbikPWmnk72jX1PlA11J
            G3Auzlu8AAeJPMir4PWe/qwFRAKq829ntNsKpMXHhTGCn0MgNtsiBAu1YEDCCG2o
            bg/WzsKEj6+rqB14sffvgfLw/z+jDz3cyZeRvWilclCZ3HlCrRw2AMwFNmxaL3V/
            hLTu94PnynP1O+D5ngQZRRosQsBd46K7LeLI0ul1wVhD6xCJh+5IR+JGoKfBFAL9
            fwheyV4WPt03jtPNan+xLBGtxC0IMvMO7lT2Fmc/dPcVjRM3H6cUDK+ih4/x4XMg
            KN+bJLCWlfneg5gU6CvnSwsOtXUksuFkNdMD09rbQFoSGAilILVgyfcobDAedGtJ
            qp/imqRQbbbEnr6FxRFtaqCuNwIkrieDx2zGSHPo2nBB6l289jGrkkbcUcxafRjh
            TGgDR4gUnICYAcpRjNszlVjz5RDT3i9Vv36jdDhTk4sQaVaJpjTQ6QUckOixYSMp
            b56midore/wDSphRXHCgUXz5dFuLrtcctoYyIw0VOcuS7V+mtgs9QpgliDuyEz7S
            XgFajdGatvHaZSoteZq3aOup2bCZWrd2FvphrGpelmn9akEMbQTYscGaISxW83zt
            TB+Nok9oOZehlGST97i2cvPQ+jUfOKRI2Oqr8D4EbO3kA4pUNJEETAu/j3hxcv0=
            =aOc5
            -----END PGP MESSAGE-----
          fp: D1119E5D8F229217E32C7E7345017EA78B63F284
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
